'use strict';
// Generates platform-specific index.html files from views/game.html.
// Edit views/game.html — never edit the generated files directly.
//
// Usage: node scripts/build-html.js
//
// Marker syntax in the template:
//   <!--[WEB]--> ... <!--[/WEB]-->        kept in web output, removed from electron
//   <!--[ELECTRON]--> ... <!--[/ELECTRON]-->  kept in electron output, removed from web

const fs = require('fs');
const path = require('path');

const TEMPLATE = path.join(__dirname, '../views/game.html');
const OUTPUTS = {
  web:      path.join(__dirname, '../public/index.html'),
  electron: path.join(__dirname, '../electron-app/index.html'),
};

const HEADER = (platform) =>
  `<!-- DO NOT EDIT — generated by scripts/build-html.js from views/game.html\n` +
  `     Platform: ${platform}. Run \`npm run build-html\` to regenerate. -->\n`;

function build(template, platform) {
  const keep = platform === 'web' ? 'WEB' : 'ELECTRON';
  const drop = platform === 'web' ? 'ELECTRON' : 'WEB';

  // Remove dropped blocks (content + markers), including the trailing newline
  let out = template.replace(
    new RegExp(`[ \\t]*<!--\\[${drop}\\]-->[\\s\\S]*?<!--\\[\\/${drop}\\]-->[ \\t]*\\n?`, 'g'),
    ''
  );

  // Strip keep markers (but preserve their content), including trailing newline
  out = out.replace(new RegExp(`[ \\t]*<!--\\[${keep}\\]-->[ \\t]*\\n?`, 'g'), '');
  out = out.replace(new RegExp(`[ \\t]*<!--\\[\\/${keep}\\]-->[ \\t]*\\n?`, 'g'), '');

  // Collapse runs of 3+ blank lines left by removed blocks down to 1
  out = out.replace(/\n{3,}/g, '\n\n');

  return HEADER(platform) + out.trimStart();
}

const template = fs.readFileSync(TEMPLATE, 'utf8');

for (const [platform, outPath] of Object.entries(OUTPUTS)) {
  fs.writeFileSync(outPath, build(template, platform));
  console.log(`  wrote ${path.relative(process.cwd(), outPath)}`);
}

console.log('build-html done');
